# Generated by Django 3.1 on 2020-08-07 14:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='safasf',
            fields=[
                ('shorten_hash', models.CharField(default=core.models.get_random_alphanumeric_string, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('target_url', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='url',
        ),
    ]
