# Generated by Django 3.1 on 2020-08-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200807_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='safasf',
            new_name='Url',
        ),
    ]
