# Generated by Django 3.1 on 2020-08-07 16:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200807_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorten_hash',
            field=models.CharField(default=core.models.get_random_alphanumeric_string, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
